sudo: required

language: node_js
node_js:
  - "9"

notifications:
  email: false

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - npm install -g webpack-cli
  - npm install
  - npm run build

env:
  global:
    - IMAGE_NAME=websh
    - NODE_ENV=dev

jobs:
  include:
    - stage: docker-alpine
      env:
        - DISTRO=alpine
      script: 
        - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .
        - docker push $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO

    - stage: docker-ubuntu
      env:
        - DISTRO=ubuntu
      script: 
        - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .
        - docker push $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO

    - stage: docker-debian
      env:
        - DISTRO=debian
      script: 
        - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .
        - docker push $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO

    - stage: docker-centos
      env:
        - DISTRO=centos
      script: 
        - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .
        - docker push $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO

    - stage: docker-fedora
      env:
        - DISTRO=fedora
      script: 
        - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .
        - docker push $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO
stages:
    - alpine
    - ubuntu
    - debian
    - centos