sudo: required

language: node

services:
  - docker

before_install:
  - node --version
  - npm --version
  - npm install -g webpack-cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

env:
  - IMAGE_NAME=websh

jobs:
  include:
    - stage: docker-alpine
      env:
        - DISTRO=alpine
      script: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .

    - stage: docker-ubuntu
      env:
        - DISTRO=ubuntu
      script: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .

    - stage: docker-debian
      env:
        - DISTRO=debian
      script: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .

    - stage: docker-centos
      env:
        - DISTRO=centos
      script: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DISTRO -f docker/$DISTRO/Dockerfile .

- stages:
    - alpine
    - ubuntu
    - debian
    - centos